name: calendar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.8
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.3
  provider: ^6.1.5+1
  weather: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: googleSans
      fonts:
        - asset: fonts/GoogleSans-VariableFont_GRAD,opsz,wght.ttf
          weight: 700
